---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws-secret-access-key: AgCaJsKUjzzVHOlkPxXf3UFSGZ7P/lW0vzKziSs+y2HYRjC4aMgHTKsQgp45kd6c9URuHs9NEJx8mzMAs7pacBB+lEtl0/h7t16IO5WRWRK81LTrx+7F333P0QUQZdVhmUSBFyWfLkcUcYTfSMmwk0kaILf8dqgdZ7RhF4bF3fNzk+K0uVT7XiJiVyxz4fQHw66qRDheDhl0R2UbuSHJ4dtdoW0TBkQiZr6nz9Ot4fQwr9ru75RRieAgbIGF+x/BbsmdPc52lvHXdyZvSTNlF9AcA7nR4mFyPnrh6AT0s6iQqgFW6ureA40AJqvZJRvQA0MmXGfHPHy/YoNs8DnOhSIMJdZjc/F6s43+qerRDwcGDmdBcV8LHk3vvl5k6sLhFPwy2gl7vOnaH6e5LmLJk9u7uxgYOLWVbxNCoCilqj1M2l64jG6l09JDYJPkMHZBABESzCGTo/dQgbnzSnhw91DsRwALRdO2WlOhr9agKkT+OG4qexHs7pPBmquiNr12tdABFNQn0X+zv5KYTIA5C26yYM7SNIxkgcLZW4DFP6dOI8zZeXIOA9TEkaZStaQcpJinX3+R2OVMH9ZGjJcCrllzzHlb4hgWvD7iu/+IpQGwVF4+Dlri9FivmGUn4LwLgMNHlW98kK9hHM2RxhK89XYm/KyQi0CbliGsUKjWRjP5YNweI2C4xPrMa0KgWSKSRIHawZ+QPSDbABT+zQ7rfryxwUoUv/nXMyXf8aORK80UotQCG1kZB5ek
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
