---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  releaseName: wordpress
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: wordpress
    version: 9.9.1
  values:
    ingress:
      enabled: true
      hostname: wordpress.starbs.net
      annotations:
        kubernetes.io/ingress.class: "nginx"
    wordpressBlogName: BOINC Workshop
    wordpressPassword: password
